// Generated by CoffeeScript 1.4.0
(function() {
  var Cell;

  Cell = (function() {

    function Cell(parent1, parent2) {
      this.state = 0;
      if ((parent1 != null) && (parent2 != null)) {
        return true;
      } else {
        return false;
      }
    }

    Cell.prototype.setState = function(newState) {
      return this.state = newState;
    };

    Cell.prototype.getState = function() {
      return this.state;
    };

    return Cell;

  })();

  try {
    window.Cell = Cell;
  } catch (error) {
    module.exports = Cell;
  }

}).call(this);
