// Generated by CoffeeScript 1.4.0
(function() {
  var addEvt, evt, evts, _i, _len;

  evts = ['set-environment-type'];

  addEvt = function(name) {
    console.log('watching', name, 'event');
    return $(document).on(name, function(event) {
      return console.log('\t\t\t\t\t\t\t\t\t\t\t\t\t\tEVENT:', event.type, ':', event);
    });
  };

  for (_i = 0, _len = evts.length; _i < _len; _i++) {
    evt = evts[_i];
    addEvt(evt);
  }

}).call(this);
