// Generated by CoffeeScript 1.4.0
(function() {

  $(document).on("set-environment-type", function(evt, selection) {
    return $(".set-environment-type-name").html(selection);
  });

}).call(this);
